[server]
port = 8501
enableCORS = false
maxUploadSize = 50  # Max file size in MB

[browser]
serverAddress = "localhost"

[runner]
magicEnabled = false  # More predictable behavior

[client]
showErrorDetails = true  # Better debugging
